drop table student if exists


CREATE TABLE STUDENT(
	NO CHAR(10) NOT NULL PRIMARY KEY,
	NAME VARCHAR(10) DEFAULT NULL,
	ENT_YEAR INT DEFAULT NULL,
	CLASS_NUM CHAR(5) DEFAULT NULL,
	IS_ATTEND BOOL DEFAULT NULL,
	SCHOOL_CD CHAR(6) DEFAULT NULL
);

INSERT INTO STUDENT(NO, NAME, ENT_EYAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2231111', '大原太郎', 2023, '131', TRUE, 'oom')
